#!/usr/bin/env bash
# .orchestra/validate.sh — Orchestra validation script
# Generated by /orchestrate init. Run: bash .orchestra/validate.sh

set -euo pipefail

ORCHESTRA_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(dirname "$ORCHESTRA_DIR")"
PASS=0; WARN=0; FAIL=0

pass() { echo "[PASS] $1"; ((PASS+=1)); }
warn() { echo "[WARN] $1"; ((WARN+=1)); }
fail() { echo "[FAIL] $1"; ((FAIL+=1)); }

# --- Check 0: Strategy config ---
check_strategy_config() {
  local strategy="$ORCHESTRA_DIR/strategy.md"
  if [ ! -f "$strategy" ]; then
    warn "strategy.md not found, skipping strategy config check"
    return
  fi

  local executor
  executor=$(grep "^executor:" "$strategy" | head -1 | sed 's/^executor: *//')

  if [ -z "$executor" ]; then
    warn "Missing executor in strategy.md (defaulting to codex for backward compatibility)"
    return
  fi

  case "$executor" in
    codex|claude)
      pass "Execution backend configured: $executor"
      ;;
    *)
      fail "Invalid executor in strategy.md: $executor (expected codex or claude)"
      ;;
  esac
}

# --- Check 0a: Core planner artifacts ---
check_core_artifacts() {
  local missing=0
  local required=(
    "$ORCHESTRA_DIR/specs/product_spec.md"
    "$ORCHESTRA_DIR/specs/review_rubric.md"
  )

  for artifact in "${required[@]}"; do
    if [ ! -f "$artifact" ]; then
      fail "Missing core artifact: ${artifact#$ORCHESTRA_DIR/}"
      ((missing+=1))
    fi
  done

  if [ "$missing" -eq 0 ]; then
    pass "Core planner artifacts present"
  fi
}

# --- Check 1: Required fields in task files ---
check_required_fields() {
  local missing=0
  local total=0
  local required_fields=("id" "title" "epic" "status" "qa_profile" "allowed_paths" "acceptance" "verification" "contract_path" "evaluation_path")

  while IFS= read -r taskfile; do
    ((total+=1))
    for field in "${required_fields[@]}"; do
      if ! grep -q "^${field}:" "$taskfile" 2>/dev/null; then
        fail "Missing field '${field}' in $(basename "$taskfile")"
        ((missing+=1))
      fi
    done
  done < <(find "$ORCHESTRA_DIR/epics" -name "T-*.md" 2>/dev/null)

  if [ "$missing" -eq 0 ] && [ "$total" -gt 0 ]; then
    pass "All required fields present ($total/$total tasks)"
  fi
}

# --- Check 1b: qa_profile values ---
check_qa_profiles() {
  local invalid=0

  while IFS= read -r taskfile; do
    local tid
    tid=$(grep "^id:" "$taskfile" | head -1 | sed 's/^id: *//')
    local profile
    profile=$(grep "^qa_profile:" "$taskfile" | head -1 | sed 's/^qa_profile: *//')

    case "$profile" in
      code|api|browser|hybrid)
        ;;
      *)
        fail "Invalid qa_profile in $tid: ${profile:-<missing>} (expected code, api, browser, or hybrid)"
        ((invalid+=1))
        ;;
    esac
  done < <(find "$ORCHESTRA_DIR/epics" -name "T-*.md" 2>/dev/null)

  if [ "$invalid" -eq 0 ]; then
    pass "All qa_profile values are valid"
  fi
}

# --- Check 2: Dependency cycles (DFS-based) ---
check_dependency_cycles() {
  local -A deps
  local -A visited
  local -A in_stack
  local has_cycle=false

  while IFS= read -r taskfile; do
    local tid
    tid=$(grep "^id:" "$taskfile" | head -1 | sed 's/^id: *//')
    local dep_line
    dep_line=$(grep "^depends_on:" "$taskfile" | head -1 | sed 's/^depends_on: *\[//;s/\].*//;s/,/ /g;s/"//g;s/'"'"'//g')
    deps["$tid"]="$dep_line"
    visited["$tid"]=0
    in_stack["$tid"]=0
  done < <(find "$ORCHESTRA_DIR/epics" -name "T-*.md" 2>/dev/null)

  dfs() {
    local node="$1"
    visited["$node"]=1
    in_stack["$node"]=1

    for dep in ${deps["$node"]:-}; do
      if [ "${in_stack[$dep]:-0}" -eq 1 ]; then
        fail "Dependency cycle: $node -> $dep"
        has_cycle=true
        return
      fi
      if [ "${visited[$dep]:-0}" -eq 0 ]; then
        dfs "$dep"
      fi
    done

    in_stack["$node"]=0
  }

  for tid in "${!deps[@]}"; do
    if [ "${visited[$tid]}" -eq 0 ]; then
      dfs "$tid"
    fi
  done

  if [ "$has_cycle" = false ]; then
    pass "No dependency cycles found"
  fi
}

# --- Check 3: Orphan dependencies ---
check_orphan_deps() {
  local -A all_ids
  local orphans=0

  while IFS= read -r taskfile; do
    local tid
    tid=$(grep "^id:" "$taskfile" | head -1 | sed 's/^id: *//')
    all_ids["$tid"]=1
  done < <(find "$ORCHESTRA_DIR/epics" -name "T-*.md" 2>/dev/null)

  while IFS= read -r taskfile; do
    local tid
    tid=$(grep "^id:" "$taskfile" | head -1 | sed 's/^id: *//')
    local dep_line
    dep_line=$(grep "^depends_on:" "$taskfile" | head -1 | sed 's/^depends_on: *\[//;s/\].*//;s/,/ /g;s/"//g;s/'"'"'//g')

    for dep in $dep_line; do
      dep=$(echo "$dep" | xargs)
      [ -z "$dep" ] && continue
      if [ -z "${all_ids[$dep]:-}" ]; then
        fail "Orphan dependency: $tid depends on $dep which does not exist"
        ((orphans+=1))
      fi
    done
  done < <(find "$ORCHESTRA_DIR/epics" -name "T-*.md" 2>/dev/null)

  if [ "$orphans" -eq 0 ]; then
    pass "No orphan dependencies found"
  fi
}

# --- Check 4: Stale base_revision ---
check_stale_revisions() {
  local stale=0
  local stale_list=""
  local current_head
  current_head=$(git -C "$REPO_ROOT" rev-parse HEAD 2>/dev/null || echo "no-git")

  if [ "$current_head" = "no-git" ]; then
    warn "Not a git repository, skipping revision check"
    return
  fi

  while IFS= read -r taskfile; do
    local tid
    tid=$(grep "^id:" "$taskfile" | head -1 | sed 's/^id: *//')
    local status
    status=$(grep "^status:" "$taskfile" | head -1 | sed 's/^status: *//')
    local base_rev
    base_rev=$(grep "^base_revision:" "$taskfile" | head -1 | sed 's/^base_revision: *//')

    if [[ "$status" =~ ^(ready|in_progress|ready_for_review)$ ]] && [ -n "$base_rev" ]; then
      if [ "$base_rev" != "$current_head" ]; then
        local allowed
        allowed=$(sed -n '/^allowed_paths:/,/^[a-z]/p' "$taskfile" | grep '^ *-' | sed 's/^ *- *//')
        local changed=false
        for path in $allowed; do
          if git -C "$REPO_ROOT" diff --quiet "$base_rev"..HEAD -- "$path" 2>/dev/null; then
            :
          else
            changed=true
            break
          fi
        done
        if [ "$changed" = true ]; then
          ((stale+=1))
          stale_list="$stale_list $tid"
        fi
      fi
    fi
  done < <(find "$ORCHESTRA_DIR/epics" -name "T-*.md" 2>/dev/null)

  if [ "$stale" -gt 0 ]; then
    warn "$stale tasks have stale base_revision:$stale_list"
  else
    pass "All active task revisions are current"
  fi
}

# --- Check 5: Contract gaps ---
check_contract_gaps() {
  local -A providers
  local gaps=0

  while IFS= read -r taskfile; do
    local provides_line
    provides_line=$(grep "^provides:" "$taskfile" | head -1 | sed 's/^provides: *\[//;s/\].*//;s/,/ /g;s/"//g;s/'"'"'//g')
    for p in $provides_line; do
      p=$(echo "$p" | xargs)
      [ -n "$p" ] && providers["$p"]=1
    done
  done < <(find "$ORCHESTRA_DIR/epics" -name "T-*.md" 2>/dev/null)

  while IFS= read -r taskfile; do
    local tid
    tid=$(grep "^id:" "$taskfile" | head -1 | sed 's/^id: *//')
    local consumes_line
    consumes_line=$(grep "^consumes:" "$taskfile" | head -1 | sed 's/^consumes: *\[//;s/\].*//;s/,/ /g;s/"//g;s/'"'"'//g')
    for c in $consumes_line; do
      c=$(echo "$c" | xargs)
      [ -z "$c" ] && continue
      if [ -z "${providers[$c]:-}" ]; then
        warn "Contract gap: '$c' consumed by $tid but not provided by any task"
        ((gaps+=1))
      fi
    done
  done < <(find "$ORCHESTRA_DIR/epics" -name "T-*.md" 2>/dev/null)

  if [ "$gaps" -eq 0 ]; then
    pass "All consumed contracts have providers"
  fi
}

# --- Check 6: Status consistency ---
check_status_consistency() {
  local issues=0
  local -A task_status

  while IFS= read -r taskfile; do
    local tid
    tid=$(grep "^id:" "$taskfile" | head -1 | sed 's/^id: *//')
    local status
    status=$(grep "^status:" "$taskfile" | head -1 | sed 's/^status: *//')
    task_status["$tid"]="$status"
  done < <(find "$ORCHESTRA_DIR/epics" -name "T-*.md" 2>/dev/null)

  while IFS= read -r taskfile; do
    local tid
    tid=$(grep "^id:" "$taskfile" | head -1 | sed 's/^id: *//')
    local status="${task_status[$tid]}"

    if [ "$status" = "done" ]; then
      local dep_line
      dep_line=$(grep "^depends_on:" "$taskfile" | head -1 | sed 's/^depends_on: *\[//;s/\].*//;s/,/ /g;s/"//g;s/'"'"'//g')
      for dep in $dep_line; do
        dep=$(echo "$dep" | xargs)
        [ -z "$dep" ] && continue
        local dep_status="${task_status[$dep]:-unknown}"
        if [ "$dep_status" != "done" ] && [ "$dep_status" != "unknown" ]; then
          fail "Status inconsistency: $tid is done but dependency $dep is $dep_status"
          ((issues+=1))
        fi
      done
    fi
  done < <(find "$ORCHESTRA_DIR/epics" -name "T-*.md" 2>/dev/null)

  if [ "$issues" -eq 0 ]; then
    pass "All task statuses are consistent"
  fi
}

# --- Check 7: Review artifact consistency ---
check_review_artifacts() {
  local issues=0

  while IFS= read -r taskfile; do
    local tid status contract_path evaluation_path head_revision
    tid=$(grep "^id:" "$taskfile" | head -1 | sed 's/^id: *//')
    status=$(grep "^status:" "$taskfile" | head -1 | sed 's/^status: *//')
    contract_path=$(grep "^contract_path:" "$taskfile" | head -1 | sed 's/^contract_path: *//')
    evaluation_path=$(grep "^evaluation_path:" "$taskfile" | head -1 | sed 's/^evaluation_path: *//')
    head_revision=$(grep "^head_revision:" "$taskfile" | head -1 | sed 's/^head_revision: *//')

    if [[ "$status" =~ ^(ready_for_review|done|needs_replan)$ ]]; then
      if [ -z "$contract_path" ] || [ ! -f "$REPO_ROOT/$contract_path" ]; then
        fail "Missing contract artifact for $tid ($status)"
        ((issues+=1))
      fi
    fi

    if [[ "$status" =~ ^(ready_for_review|done)$ ]]; then
      if [ -z "$head_revision" ]; then
        fail "Missing handoff head_revision for $tid ($status)"
        ((issues+=1))
      elif ! git -C "$REPO_ROOT" cat-file -e "${head_revision}^{commit}" 2>/dev/null; then
        fail "Invalid handoff head_revision for $tid ($status): $head_revision"
        ((issues+=1))
      fi
    fi

    if [ "$status" = "done" ]; then
      if [ -z "$evaluation_path" ] || [ ! -f "$REPO_ROOT/$evaluation_path" ]; then
        fail "Missing evaluation artifact for $tid (done)"
        ((issues+=1))
      fi
    fi
  done < <(find "$ORCHESTRA_DIR/epics" -name "T-*.md" 2>/dev/null)

  if [ "$issues" -eq 0 ]; then
    pass "Review artifacts are consistent with task statuses"
  fi
}

echo "========================================"
echo "  Orchestra Validation"
echo "  $(date)"
echo "========================================"
echo ""

check_strategy_config
check_core_artifacts
check_required_fields
check_qa_profiles
check_dependency_cycles
check_orphan_deps
check_stale_revisions
check_contract_gaps
check_status_consistency
check_review_artifacts

echo ""
echo "========================================"
echo "Summary: $PASS passed, $WARN warnings, $FAIL failures"
echo "========================================"

[ "$FAIL" -gt 0 ] && exit 1
exit 0
